### ISSUE TITLE
package directory 'capstone' does not exist

### ISSUE THREAD

**Issue by Wenzel** [scudette/rekall-capstone#1]
Hi !

i'm trying to port this package to Python3 since it's a dependency of `rekall-core`.

When i try to build this package, i have the following error message :
~~~
$ python3 setup.py build
running build
running build_py
error: package directory 'capstone' does not exist
~~~

Looking at the setup.py
~~~Python
...
setup(
    provides=['capstone'],
    packages=['capstone'],
    name='rekall-capstone',
    version=VERSION,
    author='Nguyen Anh Quynh',
    author_email='aquynh@gmail.com',
    description='Capstone disassembly engine',
    url='http://www.capstone-engine.org',
    classifiers=[
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
    ],
    requires=['ctypes'],
...
~~~

Am i supposed to clone `capstone` at the root directory or something ?
Because `capstone_source` is already there, so .. ?

I tried to replace `packages=['capstone']` by `packages=['capstone_source/bindings/python/capstone']`, and it worked.

But i'm not sure that's what i was supposed to do here.

Thanks !

**Comment by scudette** [comment]
You see here
https://github.com/scudette/rekall-capstone/blob/master/setup.py#L76

that the code already does this for you. You are supposed to build a sdist first, then use pip to build the sdist (i.e. you cant build from the checkout tree you can only build from a source distribution).

**Comment by Wenzel** [comment]
Thanks for your reply, a PR #2  is on it's way !
